services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d
  - echo "Waiting for Semaphore to become availale."
  - until $(curl --insecure --output /dev/null --silent --head --fail https://localhost/) ; do echo -n "." ; sleep 1 ; done

script:
  - bats tests/

notifications:
email: false
