services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d
  - echo "Waiting for Semaphore to become availale."
  - sleep 30
  - until $(curl --insecure --output /dev/null --silent --head --fail https://localhost/) ; do echo -n "." ; sleep 1 ; done

script:
  - bats tests/
  - grep -- '^  [a-z]' docker-compose.yml | xargs | sed 's/://g;s/ /]->[/g;s/^/[/;s/$/]/' > input
  - cat input
  - docker run -v $(pwd):/data tsub/graph-easy /data/input

notifications:
email: false
