services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d
  - echo "Waiting for Semaphore to become availale."
  - sleep 30
  - until $(curl --insecure --output /dev/null --silent --head --fail https://localhost/) ; do echo -n "." ; sleep 1 ; done

script:
  - bats tests/
  - grep -- '^  [a-z]' docker-compose.yml > a
  - cut -d: -f1 a > b
  - xargs b > c
  - sed 's/ /]->[/g;s/^/[/;s/$/]/' c > input
  - docker run -v $(pwd):/data tsub/graph-easy /data/input

notifications:
email: false
