version: '2'
services:
  httpd:
    build: ./httpd
    env_file: "variables.env"
    container_name: semaphore-httpd
    ports:
      - 80:80
      - 443:443
  semaphore:
    build: ./semaphore
    env_file: "variables.env"
    container_name: semaphore
  mysql:
    image: mysql
    env_file: "variables.env"
    container_name: semaphore-mysql
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d
